version: "3.9"

services:
 db:
  image: mongo
  ports:
   - "27017:27017"
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example

 elastic:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
  environment:
   - discovery.type=single-node
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ports:
   - "9200:9200"