version: "3.9"

services:
 db:
  image: mongo:3.4.4
  ports:
   - "27017:27017"

 elastic:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
  environment:
   - discovery.type=single-node
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ports:
   - "9200:9200"